# Generated by Django 6.0.6 on 2026-06-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('susep_code', models.CharField(blank=True, max_length=50, verbose_name='código SUSEP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
            ],
            options={
                'verbose_name': 'seguradora',
                'verbose_name_plural': 'seguradoras',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'name'), name='unique_insurer_per_brokerage')],
            },
        ),
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='código SUSEP')),
                ('category', models.CharField(choices=[('auto', 'Auto'), ('life', 'Vida'), ('property', 'Residencial'), ('business', 'Empresarial'), ('travel', 'Viagem'), ('health', 'Saúde'), ('other', 'Outros')], max_length=20, verbose_name='categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
            ],
            options={
                'verbose_name': 'ramo',
                'verbose_name_plural': 'ramos',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'name'), name='unique_lob_per_brokerage')],
            },
        ),
    ]
