name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy-to-huggingface:
    name: Sync to Hugging Face
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # Baixa os arquivos LFS do seu GitHub se houver

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions-bot@example.com"
          git config --global user.name "GitHub Actions Bot"
          
          # Garante que o Git LFS está instalado no sistema
          git lfs install
          
          # Clone usando o token de forma segura
          git clone https://x-access-token:$HF_TOKEN@huggingface.co/spaces/caio007/scsi hf_space_dir
          
          # Remove arquivos antigos do Space mantendo apenas a pasta .git
          find hf_space_dir -maxdepth 1 ! -name 'hf_space_dir' ! -name '.git' -exec rm -rf {} +
          
          # Copia todos os arquivos da raiz do repositório GitHub para a pasta do Space
          # Exclui a própria pasta temporária 'hf_space_dir' e a pasta '.git' do GitHub para não duplicar
          rsync -av --exclude='hf_space_dir' --exclude='.git' ./ hf_space_dir/
          
          cd hf_space_dir
          
          # Garante o rastreamento dos arquivos grandes no Space antes do commit
          git lfs install --local
          git lfs track
          
          git add .
          
          if ! git diff-index --quiet HEAD; then
            git commit -m "Deploy automático: ${{ github.event.head_commit.message }}"
            
            # Força o push explicitamente para a branch main do Hugging Face
            git push https://caio007:$HF_TOKEN@huggingface.co/spaces/caio007/scsi main
          else
            echo "Nenhuma alteração detectada no repositório."
          fi
