# Generated by Django 6.0.6 on 2026-06-24 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('auto', 'Auto'), ('property', 'Residencial'), ('fleet', 'Frota'), ('travel', 'Viagem'), ('life', 'Vida'), ('equipment', 'Equipamento'), ('other', 'Outro')], max_length=20, verbose_name='tipo')),
                ('description', models.CharField(max_length=300, verbose_name='descrição')),
                ('identifier', models.CharField(blank=True, max_length=100, verbose_name='identificador (placa/chassi/endereço)')),
                ('insured_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor segurado')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='atributos')),
                ('coverages', models.JSONField(blank=True, default=dict, verbose_name='coberturas')),
            ],
            options={
                'verbose_name': 'item segurado',
                'verbose_name_plural': 'itens segurados',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(max_length=30, verbose_name='número')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('under_analysis', 'Em Análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('converted', 'Convertida')], default='draft', max_length=20, verbose_name='status')),
                ('net_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='prêmio líquido')),
                ('total_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='prêmio total')),
                ('iof', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IOF')),
                ('proposed_start_date', models.DateField(blank=True, null=True, verbose_name='início proposto')),
                ('proposed_end_date', models.DateField(blank=True, null=True, verbose_name='fim proposto')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='condições de pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='resumo IA')),
                ('ai_summary_status', models.CharField(choices=[('idle', 'Aguardando'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='idle', max_length=12, verbose_name='status resumo IA')),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='resumo IA atualizado em')),
            ],
            options={
                'verbose_name': 'proposta',
                'verbose_name_plural': 'propostas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('policy_number', models.CharField(max_length=30, verbose_name='número da apólice')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('canceled', 'Cancelada'), ('expired', 'Expirada'), ('renewed', 'Renovada')], default='active', max_length=20, verbose_name='status')),
                ('net_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='prêmio líquido')),
                ('total_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='prêmio total')),
                ('iof', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IOF')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taxa de comissão (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='início vigência')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim vigência')),
                ('payment_info', models.CharField(blank=True, max_length=200, verbose_name='dados de pagamento')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='resumo IA')),
                ('ai_summary_status', models.CharField(choices=[('idle', 'Aguardando'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='idle', max_length=12, verbose_name='status resumo IA')),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='resumo IA atualizado em')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_agent', to=settings.AUTH_USER_MODEL)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client')),
            ],
            options={
                'verbose_name': 'apólice',
                'verbose_name_plural': 'apólices',
                'ordering': ('-created_at',),
            },
        ),
    ]
