# Generated by Django 6.0.6 on 2026-06-24 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('insurance', '0001_initial'),
        ('insurers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.insurer'),
        ),
        migrations.AddField(
            model_name='policy',
            name='line_of_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.lineofbusiness'),
        ),
        migrations.AddField(
            model_name='policy',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_producer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='covereditem',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covered_items', to='insurance.policy'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_as_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='brokerage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='clients.client'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.insurer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='line_of_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.lineofbusiness'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_as_producer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='insurance.proposal'),
        ),
        migrations.AddField(
            model_name='covereditem',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covered_items', to='insurance.proposal'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('brokerage', 'number'), name='unique_proposal_number_per_brokerage'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('brokerage', 'policy_number'), name='unique_policy_number_per_brokerage'),
        ),
        migrations.AddConstraint(
            model_name='covereditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('proposal__isnull', False), ('policy__isnull', True)), models.Q(('proposal__isnull', True), ('policy__isnull', False)), _connector='OR'), name='covered_item_exactly_one_parent'),
        ),
    ]
