# Generated by Django 6.0.6 on 2026-06-24 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('renewed', 'Renovada'), ('lost', 'Perdida'), ('not_renewed', 'Não Renovada')], default='pending', max_length=15, verbose_name='status')),
                ('due_date', models.DateField(verbose_name='data de vencimento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
                ('new_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='insurance.policy', verbose_name='nova apólice')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='insurance.policy', verbose_name='apólice original')),
            ],
            options={
                'verbose_name': 'renovação',
                'verbose_name_plural': 'renovações',
                'ordering': ('due_date',),
                'indexes': [models.Index(fields=['brokerage', 'status'], name='insurance_r_brokera_95caf4_idx'), models.Index(fields=['brokerage', 'due_date'], name='insurance_r_brokera_33f4fb_idx')],
            },
        ),
    ]
