# Generated by Django 6.0.6 on 2026-06-24 01:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='preço')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível')),
                ('max_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='máx. usuários')),
                ('max_clients', models.PositiveIntegerField(blank=True, null=True, verbose_name='máx. clientes')),
                ('max_policies', models.PositiveIntegerField(blank=True, null=True, verbose_name='máx. apólices')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='funcionalidades')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('legal_name', models.CharField(max_length=200, verbose_name='razão social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('susep_code', models.CharField(blank=True, max_length=50, verbose_name='código SUSEP')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_brokerages', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brokerages', to='tenants.plan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'corretora',
                'verbose_name_plural': 'corretoras',
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('past_due', 'Inadimplente'), ('canceled', 'Cancelado')], default='active', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('brokerage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.brokerage', verbose_name='corretora')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.plan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
            },
        ),
    ]
