# Generated by Django 6.0.6 on 2026-06-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('endorsement_number', models.CharField(max_length=30, verbose_name='número do endosso')),
                ('type', models.CharField(choices=[('increase', 'Acréscimo'), ('decrease', 'Redução'), ('cancellation', 'Cancelamento'), ('data_change', 'Alteração de dados')], max_length=20, verbose_name='tipo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('premium_change', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='variação do prêmio')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='data de vigência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('applied', 'Aplicado'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'endosso',
                'verbose_name_plural': 'endossos',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('claim_number', models.CharField(max_length=30, verbose_name='número do sinistro')),
                ('occurrence_date', models.DateField(verbose_name='data da ocorrência')),
                ('notice_date', models.DateField(blank=True, null=True, verbose_name='data do aviso')),
                ('status', models.CharField(choices=[('opened', 'Aberto'), ('under_analysis', 'Em análise'), ('approved', 'Aprovado'), ('denied', 'Negado'), ('paid', 'Pago'), ('closed', 'Fechado')], default='opened', max_length=20, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor reclamado')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor aprovado')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='resumo IA')),
                ('ai_summary_status', models.CharField(choices=[('idle', 'Ocioso'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='idle', max_length=12, verbose_name='status do resumo IA')),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='resumo IA atualizado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
            ],
            options={
                'verbose_name': 'sinistro',
                'verbose_name_plural': 'sinistros',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
