# Generated by Django 6.0.6 on 2026-06-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('insurance', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='covered_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.covereditem'),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.policy'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='brokerage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endorsements', to='insurance.policy'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['brokerage'], name='claims_clai_brokera_fecec4_idx'),
        ),
        migrations.AddIndex(
            model_name='endorsement',
            index=models.Index(fields=['brokerage'], name='claims_endo_brokera_6c4e78_idx'),
        ),
    ]
