# Generated by Django 6.0.6 on 2026-06-24 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='tipo de pessoa')),
                ('name', models.CharField(max_length=200, verbose_name='nome / razão social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('document', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF / CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='resumo IA')),
                ('ai_summary_status', models.CharField(choices=[('idle', 'Aguardando'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='idle', max_length=12, verbose_name='status resumo IA')),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='resumo IA atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['brokerage', 'name'], name='clients_cli_brokera_704036_idx')],
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'document'), name='client brokerage document unique')],
            },
        ),
    ]
