# Generated by Django 6.0.6 on 2026-06-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0002_initial'),
        ('partners', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='prêmio base')),
                ('insurer_rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='taxa seguradora (%)')),
                ('insurer_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor recebido')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebida'), ('paid', 'Paga')], default='pending', max_length=10, verbose_name='status')),
                ('reference_date', models.DateField(verbose_name='data de referência')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='insurance.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ('-reference_date',),
            },
        ),
        migrations.CreateModel(
            name='CommissionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('beneficiary_type', models.CharField(choices=[('agent', 'Agente'), ('producer', 'Produtor')], max_length=10, verbose_name='tipo beneficiário')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='taxa repasse (%)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor repasse')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago')], default='pending', max_length=10, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_splits', to='partners.agent', verbose_name='agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='commissions.commission', verbose_name='comissão')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_splits', to='partners.producer', verbose_name='produtor')),
            ],
            options={
                'verbose_name': 'repasse',
                'verbose_name_plural': 'repasses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'status'], name='commissions_brokera_fc6275_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'reference_date'], name='commissions_brokera_d379da_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionsplit',
            index=models.Index(fields=['brokerage', 'status'], name='commissions_brokera_597699_idx'),
        ),
    ]
