# Generated by Django 6.0.6 on 2026-06-24 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('type', models.CharField(choices=[('ai_summary', 'Resumo IA'), ('report', 'Relatório'), ('renewal', 'Renovação'), ('system', 'Sistema')], max_length=15, verbose_name='tipo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['brokerage', 'user', 'is_read'], name='notificatio_brokera_2ae560_idx')],
            },
        ),
    ]
