name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy-to-huggingface:
    name: Sync to Hugging Face
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Verificar se o Token Existe
        run: |
          if [ -z "${{ secrets.HF_TOKEN }}" ]; then
            echo "=========================================================="
            echo "❌ ERRO CRÍTICO: O seu HF_TOKEN está VAZIO ou NÃO EXISTE!"
            echo "O GitHub não encontrou o Secret configurado."
            echo "=========================================================="
            exit 1
          fi

      - name: Push to Hugging Face Space
        run: |
          # Inicializa o LFS
          git lfs install
          
          # Passa o token diretamente na URL de destino de forma segura
          git remote add hf https://SUPERCAI0:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/SUPERCAI0/scsi
          
          # Envia os arquivos
          git push --force hf main