name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy-to-huggingface:
    name: Sync to Hugging Face
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # Garante que arquivos grandes de IA sejam baixados

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configura o Git LFS (obrigatório para o Hugging Face)
          git lfs install
          
          # Adiciona o Hugging Face como um repositório remoto chamado 'hf'
          git remote add hf https://SUPERCAI0:$HF_TOKEN@huggingface.co/spaces/SUPERCAI0/scsi
          
          # Envia os arquivos da sua branch atual (main) para a branch main do Hugging Face
          # O parâmetro --force garante a sobrescrevência mesmo que o Space esteja vazio ou desalinhado
          git push --force hf main
